### ISSUE TITLE
Swag Nginx .conf file

### ISSUE THREAD

**Issue by mjeshurun** [openspeedtest/Nginx-Configuration#1]
Hi Vishnu, 
Thank you for creating and maintaining this great speed test tool.
I would like to install your speed test app on my UnRAID server and host it using Nginx and an external URL from my domain to run speedtests for my server when I'm using an external connection. 
Since I'm currently using Swag as a reverse proxy, I wanted to ask if the Nginx configuration file you shared will work also for Swag? 
Sorry if this question might seem obvious to programmers, but I'm not a programmer and I've just started my journey in the land of self-hosted servers. Which means that in many things my knowledge is still non existent.
Hope you can assist.

**Comment by openspeedtest** [comment]
Openspeedtest is available as a community plugin on Unraid. Or you can use my docker image. So you don't need to configure your own Nginx Server. 
I have not used swag, but trafik proxy and Nginx proxy manager working fine with openspeedtest docker image. 
Any reverse proxy should work. But in Trafik we need to manually setup post body content length limits. I think it's a bug on Trafik proxy. It should work without any additional configuration. Nginx proxy manager worked without any additional configurations. 
Give it a try, it should work. Docker image using same Nginx configuration posted here. And let me know.

**Comment by mjeshurun** [comment]
Thank you for your reply.
As I'm not a programmer, I'm not sure how to convert your nginx conf suggested file to a version that will work with Swag. 
I will try to ask for assistance on the Swag forum.
