### ISSUE TITLE
Upload speed is weird

### ISSUE THREAD

**Issue by tarokeitaro** [openspeedtest/Nginx-Configuration#5]
i use nginx for this.
here is the screenshot. am i wrong?
![image](https://github.com/openspeedtest/Nginx-Configuration/assets/42670754/40b6653e-f795-4215-95aa-0430f41ba82c)

![image](https://github.com/openspeedtest/Nginx-Configuration/assets/42670754/501008ea-0f69-410e-ae74-713f065e071c)

**Comment by openspeedtest** [comment]
Yes, add `client_max_body_size 35m;`  & `error_page  405     =200 $uri;`  use this configuration https://github.com/openspeedtest/Nginx-Configuration/blob/main/OpenSpeedTest-Server.conf

**Comment by tarokeitaro** [comment]
i set `client_max_body_size 35m;` and `error_page 405 =200 $uri;` but it gets weirder
![image](https://github.com/openspeedtest/Nginx-Configuration/assets/42670754/68aaff29-1286-437c-8c27-56bcc802c3e6)

**Comment by openspeedtest** [comment]
What is your protocol? You should use HTTP/1.1. If you want to use HTTP/2 or HTTP/3, you need to proxypass the upload path. This is clearly mentioned in the Nginx configuration. Please take a look at my Nginx configuration or simply replace your configuration with mine."

**Comment by openspeedtest** [comment]
@KonRay If you are using the Docker image, you do not need to make any changes. Simply run the image, and it will function without any issues. If you are creating your own image, use the posted Nginx configuration. If you need to place the OpenSpeedTest Server behind a reverse proxy, you may need to make additional configuration changes to the reverse proxy, depending on the specific reverse proxy you are using. This may include increasing the post body content length or choose HTTP/1.1 for OpenSpeedTest. Let me know more details about your issue.

**Comment by openspeedtest** [comment]
@KonRay Look at the Nginx Proxy Manager Documentation. It depends on the proxy.

**Comment by openspeedtest** [comment]
check this post https://github.com/openspeedtest/Nginx-Configuration/issues/9 No special config needed.
